# Generated by Django 5.0.6 on 2024-06-06 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100, null=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('correo_electronico', models.EmailField(max_length=254, null=True, unique=True)),
                ('numero_identificacion', models.CharField(max_length=50, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('num_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('año', models.IntegerField(null=True)),
                ('numero_de_serie', models.CharField(max_length=40, unique=True)),
                ('color', models.CharField(max_length=20)),
                ('placas', models.CharField(max_length=20, unique=True)),
                ('kilometraje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_contrato', models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=25)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avcapp.clientes')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avcapp.unidades')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TRANSFERENCIA_BANCARIA', 'Transferencia Bancaria')], max_length=80)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avcapp.contrato')),
            ],
        ),
    ]
