# Generated by Django 5.0.6 on 2024-06-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avcapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidades',
            old_name='placas',
            new_name='placa',
        ),
    ]
