# Generated by Django 5.0.6 on 2024-06-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avcapp', '0002_rename_placas_unidades_placa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'permissions': [('can_finalize_contract', 'Puede finalizar contratos')]},
        ),
    ]
